
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:sqlserver://localhost:1433;databaseName=tscore;encrypt=true;trustServerCertificate=true}
quarkus.datasource.db-kind=mssql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:sa}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:jASD32m423Jne3}

quarkus.oidc.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL:http://localhost:8080/realms/tscore}
quarkus.oidc.client-id=${QUARKUS_OIDC_CLIENT_ID:tscore}
quarkus.oidc.credentials.secret=${QUARKUS_OIDC_CREDENTIALS_SECRET:qwU7AIE7ufTMjGjvspVyP6G3e1AGMfQs}
quarkus.oidc.application-type=${QUARKUS_OIDC_APPLICATION_TYPE:service}
quarkus.oidc.token.issuer=${QUARKUS_OIDC_TOKEN_ISSUER:any}
quarkus.oidc.roles.source=${QUARKUS_OIDC_ROLES_SOURCE:accesstoken}

quarkus.rest-client.keycloak-auth.url=${QUARKUS_REST_CLIENT_KEYCLOAK_AUTH_URL:http://localhost:8080/realms/tscore/protocol/openid-connect}
quarkus.rest-client.keycloak-token.url=${QUARKUS_REST_CLIENT_KEYCLOAK_TOKEN_URL:http://localhost:8080/realms/tscore/protocol/openid-connect}

quarkus.rest-client.mailing-service.url=${QUARKUS_REST_CLIENT_MAILING_SERVICE_URL:http://localhost:9090}



quarkus.http.port=${QUARKUS_HTTP_PORT:8081}
quarkus.transaction-manager.enable-recovery=true

quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=DEBUG
quarkus.log.category."com.tscore".level=DEBUG
quarkus.http.access-log.enabled=true

quarkus.http.cors=true
quarkus.http.cors.origins=${QUARKUS_HTTP_CORS_ORIGINS:http://localhost:4200}
quarkus.http.cors.methods=${QUARKUS_HTTP_CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
quarkus.http.cors.headers=${QUARKUS_HTTP_CORS_HEADERS:accept,authorization,content-type,x-requested-with}

keycloak.client.id=${KEYCLOAK_CLIENT_ID}
keycloak.client.secret=${KEYCLOAK_CLIENT_SECRET}

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body.limit=10000
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG




